---
title: "MiniProject 4"
author: "Leigh Tanji, Samantha Bryce"
date: "2017年11月29日"
output: html_document
---

#Loading libraries
```{r}
suppressMessages(library(mdsr))
suppressMessages(library(RMySQL))
suppressMessages(library(dplyr))
suppressMessages(library(ggplot2))
```

Getting directors 
```{r, message=FALSE, echo=FALSE}
all_directors <- dbConnect_scidb(dbname = "imdb")
class(all_directors)

all_directors <- all_directors %>%
  dbGetQuery("SELECT person_id, movie_id, role_id
             FROM cast_info 
             WHERE role_id = 8;")
```

Filing in Movie titles in `directors` table
```{r}
movies <- dbConnect_scidb(dbname = "imdb")
class(movies)


movies <- movies %>%
  dbGetQuery("SELECT id, title, kind_id, production_year
             FROM title
             WHERE kind_id = 1;")


list2env(movies, envir = .GlobalEnv)
movies <- rename(movies, movie_id = id)


movie_directors <- all_directors %>%
  inner_join(movies, by = "movie_id")
```

Combining information about the directors to the 'movie_directors' table. 
```{r}
director_info <- dbConnect_scidb(dbname = "imdb")
class(director_info)


director_info <- director_info %>%
  dbGetQuery("SELECT id, name, gender 
             FROM imdb.name 
             WHERE gender = 'f';")


list2env(movies, envir = .GlobalEnv)
director_info<- rename(director_info, person_id = id)


female_directors <- movie_directors %>%
  inner_join(director_info, by = "person_id")
```

Clean Up the table od female directors and look at their number of movie productions per year.
```{r}
female_director_no <- female_directors %>%
  select(production_year, title, name) %>%
  group_by(production_year) %>%
  filter(production_year >= 1896 & production_year <= 2017) %>%
  summarize(female_director = n())
```

```{r, message=FALSE, error= FALSE, echo=FALSE}
female_directors_year <- ggplot(female_director_no, aes(x = production_year, y = female_director)) + 
  geom_point(alpha = .3) + 
  ylab("Number of films directed by women") + 
  xlab("Production Year") + 
  ggtitle("Number of films produced by women per year") +
  geom_line() +
  annotate("text", x = 1950, y = 5688, label = "2016 had most films (5688) directed by women", colour = "red", size = 2.5)

female_directors_year
```



















